export interface EmojiIcon {
  ch: string
  name: string
}

export const DATE_ICONS: EmojiIcon[] = [
  // Birthdays & Celebrations
  { ch: '🎂', name: 'birthday cake celebration' },
  { ch: '🎁', name: 'gift present birthday' },
  { ch: '🎉', name: 'party celebration confetti' },
  { ch: '🥳', name: 'party face birthday celebrate' },
  { ch: '🎈', name: 'balloon birthday party' },
  { ch: '🎀', name: 'ribbon bow gift' },
  { ch: '🪅', name: 'pinata fiesta party' },
  { ch: '🎊', name: 'confetti ball celebration' },
  // Love & Relationships
  { ch: '❤️', name: 'heart love' },
  { ch: '💕', name: 'two hearts love couple' },
  { ch: '💍', name: 'ring wedding engagement anniversary' },
  { ch: '👫', name: 'couple people together' },
  { ch: '👪', name: 'family parents children' },
  { ch: '🤗', name: 'hug hugging friends' },
  { ch: '💌', name: 'love letter valentines anniversary' },
  { ch: '🌹', name: 'rose flower love romance' },
  // Milestones & Achievements
  { ch: '🏆', name: 'trophy achievement award milestone' },
  { ch: '🥇', name: 'gold medal first prize winner' },
  { ch: '🎓', name: 'graduation university school education' },
  { ch: '🚀', name: 'rocket launch milestone achievement' },
  { ch: '⭐', name: 'star special achievement' },
  { ch: '🌟', name: 'glowing star milestone' },
  { ch: '🔥', name: 'fire streak milestone hot' },
  { ch: '💪', name: 'muscle strength milestone fitness' },
  // Calendar & Time
  { ch: '📅', name: 'calendar date schedule reminder' },
  { ch: '⏰', name: 'alarm clock reminder time' },
  { ch: '🗓️', name: 'spiral calendar planning schedule' },
  { ch: '📌', name: 'pin reminder note' },
  // Nature & Seasons
  { ch: '🌸', name: 'cherry blossom spring flower' },
  { ch: '🌞', name: 'sun summer holiday' },
  { ch: '🍂', name: 'autumn leaves fall season' },
  { ch: '❄️', name: 'snowflake winter cold' },
  { ch: '🌈', name: 'rainbow pride special' },
  // Food & Drinks
  { ch: '🍾', name: 'champagne bottle celebration toast' },
  { ch: '🥂', name: 'clinking glasses toast cheers' },
  { ch: '🍰', name: 'shortcake cake dessert birthday' },
  { ch: '🎆', name: 'fireworks new year celebration' },
  // Health & Wellness
  { ch: '🏥', name: 'hospital medical health appointment' },
  { ch: '💊', name: 'pill medicine pharmacy' },
  { ch: '🦷', name: 'tooth dentist dental' },
  { ch: '👁️', name: 'eye optician vision checkup' },
  { ch: '🩺', name: 'stethoscope doctor checkup' },
  // Travel & Fun
  { ch: '✈️', name: 'airplane flight travel vacation' },
  { ch: '🏖️', name: 'beach vacation holiday summer' },
  { ch: '🏔️', name: 'mountain hiking outdoor adventure' },
  { ch: '🚗', name: 'car road trip travel' },
  { ch: '🎮', name: 'game controller gaming fun' },
  { ch: '🎵', name: 'music note concert event' },
  // Seasonal & Holidays
  { ch: '🎃', name: 'halloween pumpkin october' },
  { ch: '🎄', name: 'christmas tree december holiday' },
  { ch: '🕎', name: 'hanukkah menorah jewish holiday' },
  { ch: '🎋', name: 'tanabata tree japanese festival' },
  { ch: '🎑', name: 'moon viewing japanese autumn festival' },
  { ch: '🥚', name: 'easter egg spring holiday' },
  { ch: '🧨', name: 'firecracker new year celebration' },
  { ch: '🎇', name: 'sparkler fireworks celebration' },
  // People & Relationships
  { ch: '👶', name: 'baby newborn infant birth' },
  { ch: '🧒', name: 'child kid young' },
  { ch: '👦', name: 'boy son nephew' },
  { ch: '👧', name: 'girl daughter niece' },
  { ch: '🧑', name: 'person adult' },
  { ch: '👴', name: 'grandpa grandfather elderly man' },
  { ch: '👵', name: 'grandma grandmother elderly woman' },
  { ch: '🐣', name: 'hatching chick newborn birth' },
  { ch: '🤝', name: 'handshake partnership business deal' },
  // Sports & Hobbies
  { ch: '⚽', name: 'soccer football sport' },
  { ch: '🏀', name: 'basketball sport' },
  { ch: '🎸', name: 'guitar music instrument' },
  { ch: '📸', name: 'camera photography hobby' },
  { ch: '🎨', name: 'palette art painting creative' },
  { ch: '📚', name: 'books reading study education' },
  { ch: '🧩', name: 'puzzle game hobby' },
  { ch: '🏋️', name: 'weightlifting gym fitness sport' },
  { ch: '🎯', name: 'target goal achievement sport' },
  // Work & Career
  { ch: '💼', name: 'briefcase work career business' },
  { ch: '👔', name: 'tie work formal career' },
  { ch: '🖥️', name: 'computer tech work career' },
  { ch: '🔬', name: 'microscope science research lab' },
  { ch: '🔧', name: 'wrench tools repair maintenance' },
  { ch: '💰', name: 'money finance wealth salary' },
  // Animals & Pets
  { ch: '🐶', name: 'dog puppy pet' },
  { ch: '🐱', name: 'cat kitten pet' },
  { ch: '🐾', name: 'paw prints pet animal' },
  { ch: '🐠', name: 'fish tropical pet aquarium' },
  { ch: '🐇', name: 'rabbit bunny pet' },
  { ch: '🦜', name: 'parrot bird pet tropical' },
  // Religious & Spiritual
  { ch: '✝️', name: 'cross christian religion faith' },
  { ch: '☪️', name: 'crescent star islam muslim religion' },
  { ch: '✡️', name: 'star of david jewish judaism' },
  { ch: '🕉️', name: 'om hinduism buddhism spiritual' },
  { ch: '☯️', name: 'yin yang taoism balance spiritual' },
  { ch: '🕌', name: 'mosque islam muslim prayer' },
  { ch: '⛪', name: 'church christian religion' },
  { ch: '🛕', name: 'hindu temple religion worship' },
  { ch: '🕍', name: 'synagogue jewish religion' },
  { ch: '🔯', name: 'star of david jewish hexagram' },
  { ch: '☦️', name: 'orthodox cross christian' },
  { ch: '🙏', name: 'prayer hands spiritual faith blessing' },
  { ch: '📿', name: 'prayer beads rosary spiritual' },
  { ch: '🪬', name: 'hamsa hand protection spiritual amulet' },
  // Board Games & Tabletop
  { ch: '♟️', name: 'chess pawn board game strategy' },
  { ch: '🎲', name: 'dice board game tabletop roll' },
  { ch: '🃏', name: 'joker playing cards game' },
  { ch: '🀄', name: 'mahjong tiles game' },
  { ch: '🎴', name: 'flower playing cards game' },
  { ch: '🎯', name: 'darts bullseye target game' },
  { ch: '🎳', name: 'bowling pins game' },
  { ch: '🎰', name: 'slot machine casino game' },
  { ch: '🧩', name: 'puzzle jigsaw game hobby' },
  { ch: '🪀', name: 'yo-yo toy game' },
  { ch: '🪁', name: 'slingshot game toy' },
]

export const DEFAULT_ICON = '🎂'
